version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 --workers 3 --timeout 120 backend.app:app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/portfolio
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CRYPTO_KEY=${CRYPTO_KEY}
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portfolio

volumes:
  postgres_data: